### ISSUE TITLE
[request]: UX: optimize screen usage on large screens

### ISSUE THREAD

**Issue by RoelVanderPaal** [datamindedbe/datafy-roadmap#18]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
On 4k screens there is a lot of whitespace under and also to the right of the log lines.
![Screenshot 2021-05-21 at 09 38 07](https://user-images.githubusercontent.com/5472783/119101365-315c1880-ba19-11eb-99ff-a066741463b9.png)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Inspecting all the log lines would require less mouse scrolling, if more log lines are shown simultaneously on the screen. This is a minor issue, but it also does not look hard to solve.

**Are you currently working around this issue?**
Use the scroll wheel ;-)

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by stijndehaes** [comment]
@RoelVanderPaal thank you for the feedback, we are currently working on the UI. This is one of the changes that has been made.

**Comment by stijndehaes** [comment]
@RoelVanderPaal If you want to beta test our new UI, you can enable it by executing the following in your browser console: 
`localStorage.setItem('useAntDesign', 'true')`, to disable it do: `localStorage.setItem('useAntDesign', 'false')`. I am looking forward to your feedback!

**Comment by stijndehaes** [comment]
The new UI has fixed this!
