### ISSUE TITLE
[request]: UX: add row background color based on status in Task Executions list (in browser UI)

### ISSUE THREAD

**Issue by RoelVanderPaal** [datamindedbe/datafy-roadmap#19]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Give the rows in the Task Executions list a background color based on the status.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Using color, a user can see in one glimpse which Task Executions need his attention. This is a minor issue, but does not look hard to solve.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by stijndehaes** [comment]
We are in the process of streamlining our UI, everything will look a bit different. After that we can look into this
