### ISSUE TITLE
[request]: Show instance type for a task in the datafy UI

### ISSUE THREAD

**Issue by din14970** [datamindedbe/datafy-roadmap#36]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
On the page where one can review logs and metrics of a task run, it would also be convenient to see the instance type that was used to run the job. The CPU and memory of the instance are shown in the metrics tab, but this information is not stored forever and may not be accessible anymore after a while. Also jobs that run for a very short time don't have this information. I would like to be able to see for a historic run what the instance type was.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

**Are you currently working around this issue?**
Looking in the code at the dags

**Additional context**

**Attachments**

**Comment by pascal-knapen** [comment]
@din14970 You might have noticed this has already been shipped. Closing the ticket with some delay.
